# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from server.proto import akesodlp_pb2 as akesodlp__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in akesodlp_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AkesoDLPServiceStub(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/akesodlp.AkesoDLPService/Register",
            request_serializer=akesodlp__pb2.RegisterRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/akesodlp.AkesoDLPService/Heartbeat",
            request_serializer=akesodlp__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.GetPolicies = channel.unary_unary(
            "/akesodlp.AkesoDLPService/GetPolicies",
            request_serializer=akesodlp__pb2.GetPoliciesRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.GetPoliciesResponse.FromString,
            _registered_method=True,
        )
        self.PolicyUpdates = channel.unary_stream(
            "/akesodlp.AkesoDLPService/PolicyUpdates",
            request_serializer=akesodlp__pb2.PolicyUpdatesRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.PolicyUpdate.FromString,
            _registered_method=True,
        )
        self.ReportIncident = channel.unary_unary(
            "/akesodlp.AkesoDLPService/ReportIncident",
            request_serializer=akesodlp__pb2.ReportIncidentRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.ReportIncidentResponse.FromString,
            _registered_method=True,
        )
        self.DetectContent = channel.unary_unary(
            "/akesodlp.AkesoDLPService/DetectContent",
            request_serializer=akesodlp__pb2.DetectContentRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.DetectContentResponse.FromString,
            _registered_method=True,
        )
        self.GetDiscoverScans = channel.unary_unary(
            "/akesodlp.AkesoDLPService/GetDiscoverScans",
            request_serializer=akesodlp__pb2.GetDiscoverScansRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.GetDiscoverScansResponse.FromString,
            _registered_method=True,
        )
        self.ReportDiscoverResults = channel.unary_unary(
            "/akesodlp.AkesoDLPService/ReportDiscoverResults",
            request_serializer=akesodlp__pb2.ReportDiscoverResultsRequest.SerializeToString,
            response_deserializer=akesodlp__pb2.ReportDiscoverResultsResponse.FromString,
            _registered_method=True,
        )


class AkesoDLPServiceServicer(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def Register(self, request, context):
        """Agent registration — called once on startup"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Periodic heartbeat — agent reports health, server returns commands"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetPolicies(self, request, context):
        """Pull current policies for the agent"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PolicyUpdates(self, request, context):
        """Server-stream — pushes policy updates to connected agents in real time"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportIncident(self, request, context):
        """Agent reports a policy violation incident"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DetectContent(self, request, context):
        """Two-Tier Detection — agent sends content for server-side evaluation"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDiscoverScans(self, request, context):
        """Agent pulls pending discover scans assigned to it"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReportDiscoverResults(self, request, context):
        """Agent reports discover scan results back to server"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AkesoDLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=akesodlp__pb2.RegisterRequest.FromString,
            response_serializer=akesodlp__pb2.RegisterResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=akesodlp__pb2.HeartbeatRequest.FromString,
            response_serializer=akesodlp__pb2.HeartbeatResponse.SerializeToString,
        ),
        "GetPolicies": grpc.unary_unary_rpc_method_handler(
            servicer.GetPolicies,
            request_deserializer=akesodlp__pb2.GetPoliciesRequest.FromString,
            response_serializer=akesodlp__pb2.GetPoliciesResponse.SerializeToString,
        ),
        "PolicyUpdates": grpc.unary_stream_rpc_method_handler(
            servicer.PolicyUpdates,
            request_deserializer=akesodlp__pb2.PolicyUpdatesRequest.FromString,
            response_serializer=akesodlp__pb2.PolicyUpdate.SerializeToString,
        ),
        "ReportIncident": grpc.unary_unary_rpc_method_handler(
            servicer.ReportIncident,
            request_deserializer=akesodlp__pb2.ReportIncidentRequest.FromString,
            response_serializer=akesodlp__pb2.ReportIncidentResponse.SerializeToString,
        ),
        "DetectContent": grpc.unary_unary_rpc_method_handler(
            servicer.DetectContent,
            request_deserializer=akesodlp__pb2.DetectContentRequest.FromString,
            response_serializer=akesodlp__pb2.DetectContentResponse.SerializeToString,
        ),
        "GetDiscoverScans": grpc.unary_unary_rpc_method_handler(
            servicer.GetDiscoverScans,
            request_deserializer=akesodlp__pb2.GetDiscoverScansRequest.FromString,
            response_serializer=akesodlp__pb2.GetDiscoverScansResponse.SerializeToString,
        ),
        "ReportDiscoverResults": grpc.unary_unary_rpc_method_handler(
            servicer.ReportDiscoverResults,
            request_deserializer=akesodlp__pb2.ReportDiscoverResultsRequest.FromString,
            response_serializer=akesodlp__pb2.ReportDiscoverResultsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "akesodlp.AkesoDLPService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "akesodlp.AkesoDLPService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AkesoDLPService(object):
    """=============================================================================
    Service
    =============================================================================

    """

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/Register",
            akesodlp__pb2.RegisterRequest.SerializeToString,
            akesodlp__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/Heartbeat",
            akesodlp__pb2.HeartbeatRequest.SerializeToString,
            akesodlp__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetPolicies(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/GetPolicies",
            akesodlp__pb2.GetPoliciesRequest.SerializeToString,
            akesodlp__pb2.GetPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PolicyUpdates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/akesodlp.AkesoDLPService/PolicyUpdates",
            akesodlp__pb2.PolicyUpdatesRequest.SerializeToString,
            akesodlp__pb2.PolicyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportIncident(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/ReportIncident",
            akesodlp__pb2.ReportIncidentRequest.SerializeToString,
            akesodlp__pb2.ReportIncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DetectContent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/DetectContent",
            akesodlp__pb2.DetectContentRequest.SerializeToString,
            akesodlp__pb2.DetectContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDiscoverScans(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/GetDiscoverScans",
            akesodlp__pb2.GetDiscoverScansRequest.SerializeToString,
            akesodlp__pb2.GetDiscoverScansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReportDiscoverResults(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/akesodlp.AkesoDLPService/ReportDiscoverResults",
            akesodlp__pb2.ReportDiscoverResultsRequest.SerializeToString,
            akesodlp__pb2.ReportDiscoverResultsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
