# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server.proto import sentineldlp_pb2 as sentineldlp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentineldlp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentinelDLPServiceStub(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/sentineldlp.SentinelDLPService/Register',
                request_serializer=sentineldlp__pb2.RegisterRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/sentineldlp.SentinelDLPService/Heartbeat',
                request_serializer=sentineldlp__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetPolicies = channel.unary_unary(
                '/sentineldlp.SentinelDLPService/GetPolicies',
                request_serializer=sentineldlp__pb2.GetPoliciesRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.GetPoliciesResponse.FromString,
                _registered_method=True)
        self.PolicyUpdates = channel.unary_stream(
                '/sentineldlp.SentinelDLPService/PolicyUpdates',
                request_serializer=sentineldlp__pb2.PolicyUpdatesRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.PolicyUpdate.FromString,
                _registered_method=True)
        self.ReportIncident = channel.unary_unary(
                '/sentineldlp.SentinelDLPService/ReportIncident',
                request_serializer=sentineldlp__pb2.ReportIncidentRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.ReportIncidentResponse.FromString,
                _registered_method=True)
        self.DetectContent = channel.unary_unary(
                '/sentineldlp.SentinelDLPService/DetectContent',
                request_serializer=sentineldlp__pb2.DetectContentRequest.SerializeToString,
                response_deserializer=sentineldlp__pb2.DetectContentResponse.FromString,
                _registered_method=True)


class SentinelDLPServiceServicer(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def Register(self, request, context):
        """Agent registration — called once on startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Periodic heartbeat — agent reports health, server returns commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicies(self, request, context):
        """Pull current policies for the agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyUpdates(self, request, context):
        """Server-stream — pushes policy updates to connected agents in real time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportIncident(self, request, context):
        """Agent reports a policy violation incident
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectContent(self, request, context):
        """Two-Tier Detection — agent sends content for server-side evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentinelDLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=sentineldlp__pb2.RegisterRequest.FromString,
                    response_serializer=sentineldlp__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=sentineldlp__pb2.HeartbeatRequest.FromString,
                    response_serializer=sentineldlp__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicies,
                    request_deserializer=sentineldlp__pb2.GetPoliciesRequest.FromString,
                    response_serializer=sentineldlp__pb2.GetPoliciesResponse.SerializeToString,
            ),
            'PolicyUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.PolicyUpdates,
                    request_deserializer=sentineldlp__pb2.PolicyUpdatesRequest.FromString,
                    response_serializer=sentineldlp__pb2.PolicyUpdate.SerializeToString,
            ),
            'ReportIncident': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportIncident,
                    request_deserializer=sentineldlp__pb2.ReportIncidentRequest.FromString,
                    response_serializer=sentineldlp__pb2.ReportIncidentResponse.SerializeToString,
            ),
            'DetectContent': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectContent,
                    request_deserializer=sentineldlp__pb2.DetectContentRequest.FromString,
                    response_serializer=sentineldlp__pb2.DetectContentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentineldlp.SentinelDLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentineldlp.SentinelDLPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentinelDLPService(object):
    """=============================================================================
    Service
    =============================================================================

    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentineldlp.SentinelDLPService/Register',
            sentineldlp__pb2.RegisterRequest.SerializeToString,
            sentineldlp__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentineldlp.SentinelDLPService/Heartbeat',
            sentineldlp__pb2.HeartbeatRequest.SerializeToString,
            sentineldlp__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentineldlp.SentinelDLPService/GetPolicies',
            sentineldlp__pb2.GetPoliciesRequest.SerializeToString,
            sentineldlp__pb2.GetPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sentineldlp.SentinelDLPService/PolicyUpdates',
            sentineldlp__pb2.PolicyUpdatesRequest.SerializeToString,
            sentineldlp__pb2.PolicyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportIncident(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentineldlp.SentinelDLPService/ReportIncident',
            sentineldlp__pb2.ReportIncidentRequest.SerializeToString,
            sentineldlp__pb2.ReportIncidentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentineldlp.SentinelDLPService/DetectContent',
            sentineldlp__pb2.DetectContentRequest.SerializeToString,
            sentineldlp__pb2.DetectContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
